# Site settings
name: Less Or More
email: oper_0@126.com
author: oper
url: http://www.oper.fun
resume_site: https://cheng723719.github.io/
github: https://cheng723719.github.io/
baseurl: ""
description: Actually, less is more!
meta_description: 以梦为马
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: cheng723719

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

